# Generated by Django 3.2.23 on 2024-02-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reviews_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestions',
            name='QUESTION',
        ),
        migrations.AddField(
            model_name='testquestions',
            name='question',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='testquestions',
            name='type',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
